# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyrobni_program', '0002_product_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description2',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
