# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyrobni_program', '0005_categoryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vyrobni_program.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='categoryimage',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
