# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyrobni_program', '0007_auto_20160823_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='/static/')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vyrobni_program.Image'),
        ),
    ]
