# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyrobni_program', '0008_auto_20160824_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='/media/'),
        ),
    ]
