# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyrobni_program', '0010_auto_20160824_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
