# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyrobni_program', '0012_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
