# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyrobni_program', '0013_picture_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
