# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyrobni_program', '0016_picture_popis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='long_description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
