# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyrobni_program', '0019_picture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='popis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
