# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='tel',
            new_name='telefon',
        ),
    ]
