# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
            ],
        ),
    ]
